### PR TITLE
デバイスマネージャのUI改善

### PR DESCRIPTION
**Pull request by TakayukiHoshi1984**
## 確認項目
- 初回起動時にガイド画面が表示されること。
- デバイス一覧画面が表示されること。
- デバイス一覧画面からデバイス確認画面へ遷移できること。
- デバイス確認画面で、デバイスが操作できること。
- デバイス一覧画面の右上のメニューに、設定とヘルプが追加されていること。
- メニューの設定ボタンを押下することで、設定画面へ遷移すること。
- メニューのヘルプボタンを押下することで、ヘルプ画面へ遷移すること。
- ヘルプ画面で、各ページが表示されること。

### CODE REVIEW

**Comment by Onuzimoyr** [comment]
当該ブランチをビルドしようとすると、以下エラーが発生します。
原因は何か分かりますでしょうか？
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
Information:Gradle tasks [:app:assembleRelease]
Observed package id 'add-ons;addon-google_apis-google-19' in inconsistent location 'C:\Users\izanami\AppData\Local\Android\sdk\add-ons\addon-google_apis-google-19-1' (Expected 'C:\Users\izanami\AppData\Local\Android\sdk\add-ons\addon-google_apis-google-19')
com.android.build.gradle.internal.api.LibraryVariantImpl_Decorated@b76e9d8
com.android.build.gradle.internal.api.LibraryVariantImpl_Decorated@354e404b
:app:preBuild UP-TO-DATE
:app:preReleaseBuild UP-TO-DATE
:app:checkReleaseManifest
:app:preDebugBuild UP-TO-DATE
:dconnect-device-plugin-sdk:preBuild UP-TO-DATE
:dconnect-device-plugin-sdk:preReleaseBuild UP-TO-DATE
:dconnect-device-plugin-sdk:compileReleaseNdk UP-TO-DATE
:dconnect-device-plugin-sdk:compileLint
:dconnect-device-plugin-sdk:copyReleaseLint UP-TO-DATE
:dconnect-device-plugin-sdk:checkReleaseManifest
:dconnect-device-plugin-sdk:preDebugAndroidTestBuild UP-TO-DATE
:dconnect-device-plugin-sdk:preDebugBuild UP-TO-DATE
:dconnect-device-plugin-sdk:preDebugUnitTestBuild UP-TO-DATE
:dconnect-device-plugin-sdk:preReleaseUnitTestBuild UP-TO-DATE
:dconnect-sdk-for-android:preBuild UP-TO-DATE
:dconnect-sdk-for-android:preReleaseBuild UP-TO-DATE
:dconnect-sdk-for-android:compileReleaseNdk UP-TO-DATE
:dconnect-sdk-for-android:compileLint
:dconnect-sdk-for-android:copyReleaseLint UP-TO-DATE
:dconnect-sdk-for-android:checkReleaseManifest
:dconnect-sdk-for-android:preDebugAndroidTestBuild UP-TO-DATE
:dconnect-sdk-for-android:preDebugBuild UP-TO-DATE
:dconnect-sdk-for-android:preDebugUnitTestBuild UP-TO-DATE
:dconnect-sdk-for-android:preReleaseUnitTestBuild UP-TO-DATE
:dconnect-sdk-for-android:prepareComAndroidSupportSupportV42310Library UP-TO-DATE
:dconnect-sdk-for-android:prepareReleaseDependencies
:dconnect-sdk-for-android:compileReleaseAidl UP-TO-DATE
:dconnect-sdk-for-android:compileReleaseRenderscript UP-TO-DATE
:dconnect-sdk-for-android:generateReleaseBuildConfig UP-TO-DATE
:dconnect-sdk-for-android:mergeReleaseShaders UP-TO-DATE
:dconnect-sdk-for-android:compileReleaseShaders UP-TO-DATE
:dconnect-sdk-for-android:generateReleaseAssets UP-TO-DATE
:dconnect-sdk-for-android:mergeReleaseAssets UP-TO-DATE
:dconnect-sdk-for-android:generateReleaseResValues UP-TO-DATE
:dconnect-sdk-for-android:generateReleaseResources UP-TO-DATE
:dconnect-sdk-for-android:mergeReleaseResources UP-TO-DATE
:dconnect-sdk-for-android:processReleaseManifest UP-TO-DATE
:dconnect-sdk-for-android:processReleaseResources UP-TO-DATE
:dconnect-sdk-for-android:generateReleaseSources UP-TO-DATE
:dconnect-sdk-for-android:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:dconnect-sdk-for-android:compileReleaseJavaWithJavac UP-TO-DATE
:dconnect-sdk-for-android:extractReleaseAnnotations UP-TO-DATE
:dconnect-sdk-for-android:mergeReleaseProguardFiles UP-TO-DATE
:dconnect-sdk-for-android:packageReleaseRenderscript UP-TO-DATE
:dconnect-sdk-for-android:packageReleaseResources UP-TO-DATE
:dconnect-sdk-for-android:processReleaseJavaRes UP-TO-DATE
:dconnect-sdk-for-android:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:dconnect-sdk-for-android:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:dconnect-sdk-for-android:mergeReleaseJniLibFolders UP-TO-DATE
:dconnect-sdk-for-android:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:dconnect-sdk-for-android:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:dconnect-sdk-for-android:bundleRelease UP-TO-DATE
:dconnect-device-plugin-sdk:prepareComAndroidSupportSupportV42310Library UP-TO-DATE
:dconnect-device-plugin-sdk:prepareDConnectManagerDconnectSdkForAndroidUnspecifiedLibrary UP-TO-DATE
:dconnect-device-plugin-sdk:prepareReleaseDependencies
:dconnect-device-plugin-sdk:compileReleaseAidl UP-TO-DATE
:dconnect-device-plugin-sdk:compileReleaseRenderscript UP-TO-DATE
:dconnect-device-plugin-sdk:generateReleaseBuildConfig UP-TO-DATE
:dconnect-device-plugin-sdk:mergeReleaseShaders UP-TO-DATE
:dconnect-device-plugin-sdk:compileReleaseShaders UP-TO-DATE
:dconnect-device-plugin-sdk:generateReleaseAssets UP-TO-DATE
:dconnect-device-plugin-sdk:mergeReleaseAssets UP-TO-DATE
:dconnect-device-plugin-sdk:generateReleaseResValues UP-TO-DATE
:dconnect-device-plugin-sdk:generateReleaseResources UP-TO-DATE
:dconnect-device-plugin-sdk:mergeReleaseResources UP-TO-DATE
:dconnect-device-plugin-sdk:processReleaseManifest UP-TO-DATE
:dconnect-device-plugin-sdk:processReleaseResources UP-TO-DATE
:dconnect-device-plugin-sdk:generateReleaseSources UP-TO-DATE
:dconnect-device-plugin-sdk:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:dconnect-device-plugin-sdk:compileReleaseJavaWithJavac UP-TO-DATE
:dconnect-device-plugin-sdk:extractReleaseAnnotations UP-TO-DATE
:dconnect-device-plugin-sdk:mergeReleaseProguardFiles UP-TO-DATE
:dconnect-device-plugin-sdk:packageReleaseRenderscript UP-TO-DATE
:dconnect-device-plugin-sdk:packageReleaseResources UP-TO-DATE
:dconnect-device-plugin-sdk:processReleaseJavaRes UP-TO-DATE
:dconnect-device-plugin-sdk:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:dconnect-device-plugin-sdk:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:dconnect-device-plugin-sdk:mergeReleaseJniLibFolders UP-TO-DATE
:dconnect-device-plugin-sdk:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:dconnect-device-plugin-sdk:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:dconnect-device-plugin-sdk:bundleRelease UP-TO-DATE
:dconnect-server:compileJava UP-TO-DATE
:dconnect-server:processResources UP-TO-DATE
:dconnect-server:classes UP-TO-DATE
:dconnect-server:jar UP-TO-DATE
:dconnect-server-nano-httpd:preBuild UP-TO-DATE
:dconnect-server-nano-httpd:preReleaseBuild UP-TO-DATE
:dconnect-server-nano-httpd:compileReleaseNdk UP-TO-DATE
:dconnect-server-nano-httpd:compileLint
:dconnect-server-nano-httpd:copyReleaseLint UP-TO-DATE
:dconnect-server-nano-httpd:mergeReleaseProguardFiles UP-TO-DATE
:dconnect-server-nano-httpd:packageReleaseRenderscript UP-TO-DATE
:dconnect-server-nano-httpd:checkReleaseManifest
:dconnect-server-nano-httpd:prepareReleaseDependencies
:dconnect-server-nano-httpd:compileReleaseRenderscript UP-TO-DATE
:dconnect-server-nano-httpd:generateReleaseResValues UP-TO-DATE
:dconnect-server-nano-httpd:generateReleaseResources UP-TO-DATE
:dconnect-server-nano-httpd:packageReleaseResources UP-TO-DATE
:dconnect-server-nano-httpd:compileReleaseAidl UP-TO-DATE
:dconnect-server-nano-httpd:generateReleaseBuildConfig UP-TO-DATE
:dconnect-server-nano-httpd:mergeReleaseShaders UP-TO-DATE
:dconnect-server-nano-httpd:compileReleaseShaders UP-TO-DATE
:dconnect-server-nano-httpd:generateReleaseAssets UP-TO-DATE
:dconnect-server-nano-httpd:mergeReleaseAssets UP-TO-DATE
:dconnect-server-nano-httpd:processReleaseManifest UP-TO-DATE
:dconnect-server-nano-httpd:processReleaseResources UP-TO-DATE
:dconnect-server-nano-httpd:generateReleaseSources UP-TO-DATE
:dconnect-server-nano-httpd:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:dconnect-server-nano-httpd:compileReleaseJavaWithJavac UP-TO-DATE
:dconnect-server-nano-httpd:processReleaseJavaRes UP-TO-DATE
:dconnect-server-nano-httpd:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:dconnect-server-nano-httpd:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:dconnect-server-nano-httpd:mergeReleaseJniLibFolders UP-TO-DATE
:dconnect-server-nano-httpd:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:dconnect-server-nano-httpd:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:dconnect-server-nano-httpd:bundleRelease UP-TO-DATE
:app:prepareComAndroidSupportSupportV42310Library UP-TO-DATE
:app:prepareDConnectManagerDconnectDevicePluginSdkUnspecifiedLibrary UP-TO-DATE
:app:prepareDConnectManagerDconnectSdkForAndroidUnspecifiedLibrary UP-TO-DATE
:app:prepareDConnectManagerDconnectServerNanoHttpdUnspecifiedLibrary UP-TO-DATE
:app:prepareReleaseDependencies
:app:compileReleaseAidl
:app:compileReleaseRenderscript
:app:generateReleaseBuildConfig
:app:mergeReleaseShaders
:app:compileReleaseShaders
:app:generateReleaseAssets
:app:mergeReleaseAssets
:app:generateReleaseResValues UP-TO-DATE
:app:generateReleaseResources
:app:mergeReleaseResources
:app:processReleaseManifest
:app:processReleaseResources
:app:generateReleaseSources
:app:incrementalReleaseJavaCompilationSafeguard
:app:compileReleaseJavaWithJavac
:app:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
注意:一部の入力ファイルは非推奨のAPIを使用またはオーバーライドしています。
注意:詳細は、-Xlint:deprecationオプションを指定して再コンパイルしてください。
:app:compileReleaseNdk UP-TO-DATE
:app:compileReleaseSources
:app:lintVitalRelease
    <string name="activity_service_list_service_discovery">デバイスを検索中</string>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    <string name="activity_service_list_checkbox">次回からこの画面を表示しない。</string>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    <string name="activity_service_list_guide_1">Device Connect Managerを起動することができます。</string>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    <string name="activity_service_list_guide_2">Device Connect Managerの設定を行うことができます。</string>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    <string name="activity_service_list_guide_next">次へ</string>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    <string name="activity_service_list_guide_end">閉じる</string>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    <string name="activity_service_list_no_service">デバイスが接続されていません。\nプラグインから設定を行ってください。</string>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    <string name="activity_service_list_no_plugin_title">プラグイン確認</string>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    <string name="activity_service_list_no_plugin_message">プラグインが入っていないと、このDevice Connect Managerは使用できません。\nHOSTプラグインなどをインストールしてください。</string>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    <string name="activity_service_list_no_plugin_positive">はい</string>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    <string name="activity_service_list_offline_title">デバイス起動</string>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    <string name="activity_service_list_offline_message">%1sは、接続されていません。\nデバイスプラグインの設定を確認してください。</string>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    <string name="activity_service_list_offline_positive">設定を開く</string>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    <string name="activity_service_list_offline_negative">閉じる</string>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    <string name="activity_websocket_delete_title">WebSocket削除確認</string>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    <string name="activity_websocket_delete_message">WebSocketを閉じて良いでしょうか？</string>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    <string name="activity_websocket_delete_positive">はい</string>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Projects\verification\dConnectManager\dConnectManager\app\src\main\res\values-ja\strings.xml
Error:(166) Error: "activity_service_list_service_discovery" is translated here but not found in default locale [ExtraTranslation]
Error:(167) Error: "activity_service_list_checkbox" is translated here but not found in default locale [ExtraTranslation]
Error:(168) Error: "activity_service_list_guide_1" is translated here but not found in default locale [ExtraTranslation]
Error:(169) Error: "activity_service_list_guide_2" is translated here but not found in default locale [ExtraTranslation]
Error:(170) Error: "activity_service_list_guide_next" is translated here but not found in default locale [ExtraTranslation]
Error:(171) Error: "activity_service_list_guide_end" is translated here but not found in default locale [ExtraTranslation]
Error:(172) Error: "activity_service_list_no_service" is translated here but not found in default locale [ExtraTranslation]
Error:(173) Error: "activity_service_list_no_plugin_title" is translated here but not found in default locale [ExtraTranslation]
Error:(174) Error: "activity_service_list_no_plugin_message" is translated here but not found in default locale [ExtraTranslation]
Error:(175) Error: "activity_service_list_no_plugin_positive" is translated here but not found in default locale [ExtraTranslation]
Error:(176) Error: "activity_service_list_offline_title" is translated here but not found in default locale [ExtraTranslation]
Error:(177) Error: "activity_service_list_offline_message" is translated here but not found in default locale [ExtraTranslation]
Error:(178) Error: "activity_service_list_offline_positive" is translated here but not found in default locale [ExtraTranslation]
Error:(179) Error: "activity_service_list_offline_negative" is translated here but not found in default locale [ExtraTranslation]
Error:(181) Error: "activity_websocket_delete_title" is translated here but not found in default locale [ExtraTranslation]
Error:(182) Error: "activity_websocket_delete_message" is translated here but not found in default locale [ExtraTranslation]
Error:(183) Error: "activity_websocket_delete_positive" is translated here but not found in default locale [ExtraTranslation]
Error:(184) Error: "activity_websocket_delete_negative" is translated here but not found in default locale [ExtraTranslation]
    <string name="activity_websocket_delete_negative">いいえ</string>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   Explanation for issues of type "ExtraTranslation":
   If a string appears in a specific language translation file, but there is
   no corresponding string in the default locale, then this string is probably
   unused. (It's technically possible that your application is only intended
   to run in a specific locale, but it's still a good idea to provide a
   fallback.).
   Note that these strings can lead to crashes if the string is looked up on
   any locale not providing a translation, so it's important to clean them
   up.
18 errors, 0 warnings
Error:Execution failed for task ':app:lintVitalRelease'.
> Lint found fatal errors while assembling a release target.
To proceed, either fix the issues identified by lint, or modify your build script as follows:
...
android {
    lintOptions {
        checkReleaseBuilds false
        // Or, if you prefer, you can continue to check for errors in release builds,
        // but continue the build even when errors are found:
        abortOnError false
    }
}
...
Information:BUILD FAILED
Information:Total time: 26.057 secs
Information:19 errors
Information:0 warnings
Information:See complete output in console

**Comment by Onuzimoyr** [comment]
エラーとなっている箇所の記述が、strings.xml にないため、エラーが発生しているように思われます。
一度調査頂けますか？

**Comment by TakayukiHoshi1984** [comment]
Lintエラーで、リリースビルドすると発生するビルドエラーです。
別ブランチで修正していますので、デバックビルドしてもらえれば動作確認自体はできると思います。

**Comment by Onuzimoyr** [comment]
承知しました。
ただ、ブランチでプルリクエストされるのであれば、ブランチ単位でビルドが通るようにしておいて頂けると助かります。

**Comment by TakayukiHoshi1984** [comment]
失礼しました。
デバッグビルドのみで確認しておりました。

**Pull request merged**
